# -*- coding: utf-8 -*-
"""web_traffic_visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1whAJsDbJZEkXwCyEpjZvBhDYNKaSRzwi
"""

import matplotlib.pyplot as plt
import numpy as np

#data for each variables
months = ['07/2019', '08/2019', '09/2019', '10/2019', '11/2019']
searches = [50, 53, 59, 56, 62]
direct = [39, 47, 42, 51, 51]
social = [70, 80, 90, 87, 92]

#arrange the no. of months
x = np.arange(len(months))
width = 0.25

#plotting the bars
plt.figure(figsize=(10,6))
bar1 = plt.bar(x - width, searches, width, label='Searches', color='blue')
bar2 = plt.bar(x, direct, width, label='Direct', color='purple')
bar3 = plt.bar(x + width, social, width, label='Social Media', color='orange')

#loop to add numbers on top of each bar
for i in range(len(months)):
    plt.text(x[i] - width, searches[i] + 1, str(searches[i]), ha='center', va='bottom', fontsize=9)
    plt.text(x[i], direct[i] + 1, str(direct[i]), ha='center', va='bottom', fontsize=9)
    plt.text(x[i] + width, social[i] + 1, str(social[i]), ha='center', va='bottom', fontsize=9)

#labels for x/y axis and title
plt.xlabel('months')
plt.ylabel('visitors in thousands')
plt.title('Visitors by web traffic sources')
plt.xticks(x, months)
plt.ylim(0, 100)

#move the legend to the bottom
plt.legend()
plt.legend(loc='upper center', bbox_to_anchor=(0.5, -0.12), ncol=3)
plt.tight_layout()
plt.show()